### ISSUE TITLE
can't increase sub results (--subs=15)

### ISSUE THREAD

**Issue by rhurds** [pystardust/ytfzf#198]
$ ytfzf --subs=15
--subs requires a numeric arg, but was given "15"
$

**Comment by pystardust** [comment]
has it been fixed now?

**Comment by rhurds** [comment]
![Screenshot_20210409_140223](https://user-images.githubusercontent.com/81023652/114135970-97df1880-993c-11eb-8197-7463b7dc80ca.png)
Changed the ytfzf file from bin but ytfzf --subs=15 still not working,
![Screenshot_20210409_141416](https://user-images.githubusercontent.com/81023652/114137015-2607ce80-993e-11eb-99c3-c0bc0f76ef7b.png)

I also noticed that inputting ytfzf --subs= (equal sign included) gives you 30 results per subscription.

**Comment by pystardust** [comment]
have you remove the old ytfzf?
```
whereis ytfzf
```
remove ytfzf and install it again.
Have you manually edited it? It seems to be incorrect. The correct function in the master branch is.
```sh
is_non_number () {
	case $1 in
		(*[!0-9]*|'') 
			return 0;;
		(*)
			return 1;;
	esac
}
```

**Comment by rhurds** [comment]
Ok my bad, the red lines at the fix https://github.com/pystardust/ytfzf/commit/b38a4e773be332cfbf39dafc4b6810b65d0efc3d means the line has been deleted, I copied them all, lol. But I copied the code from your reply and it works now. Thanks!
