### ISSUE TITLE
[BUG]: Minor output bug after selecting video

### ISSUE THREAD

**Issue by guiltiest-gear** [pystardust/ytfzf#702]
### Describe the bug
After selecting a video to play, a blank line and the literal characters of ${new_line} show up in the output
### To Reproduce
1. Install ytfzf 2.6.1
2. Enable thumbnails in config or with command line option
3. Search for a video
4. Notice how there is a blank like after the scraping message, and the string of ${new_line} appended to Fetching thumbnails...
### Expected behavior
There should be no blank like and no extra characters
### Screenshots
![Screenshot_2023-09-17_18-47-21](https://github.com/pystardust/ytfzf/assets/79071613/2f1f3144-6bfd-4a7a-b275-aa5a1977dee0)

### Information
 - OS: EndeavourOS
 - Terminal: kitty 0.29.2
 - Ytfzf version: 2.6.1
 - Output of `readlink $(which sh)`: bash
 - (if is a thumbnail issue) run `ytfzf --thumbnail-log=log.txt` and post the file:

### Additional context
This bug doesn't occur in 2.6.0, so it must be from a commit between 2.6.0 and 2.6.1

**Comment by Euro20179** [comment]
I believe this is fixed in the development branch, you could try using that.

**Comment by guiltiest-gear** [comment]
I'll clone to the latest commit and get back to you on that

**Comment by guiltiest-gear** [comment]
Newest commit fixes ${new_line} bug, but extra blank line is still present
![Screenshot_2023-09-18_14-27-02](https://github.com/pystardust/ytfzf/assets/79071613/5d2e4dcb-2bcf-40bf-96d0-a5bf97a46c30)

**Comment by tabletseeker** [comment]
Updated and working ytfzf project here:
https://github.com/tabletseeker/ytfzf_prime
